### ISSUE TITLE
exact_butterfly_counting gives double of the res

### ISSUE THREAD

**Issue by qubotong** [beginner1010/butterfly-counting#1]
In function exact_butterfly_counting, the sum of the butterfly is calculated by
`res += hashmap_C[two_hop_neighborhood];`.
Shouldn't it be
`res += hashmap_C[two_hop_neighborhood] * 0.5;`?

Is there some consideration you took to double the exact number of butterfly?

**Comment by beginner1010** [comment]
Hi Qu,

Thank you for your message. Let me first recall what hashmap_C maintains. For every two vertices "vertex" and "two_hop_neighborhood" (which both reside in one partition), "hashmap_C[two_hop_neighborhood]" maintains the common neighbors of "vertex" and "two_hop_neighborhood". For simplicity, let **c** be hashmap_C[two_hop_neighborhood].

Therefore, (c choose 2) is the number of butterflies that contain both vertices "vertex" and "two_hop_neighborhoood". Instead of computing (c choose 2) directly, we compute it incrementally, just for more optimization. 

In general, (x + 1 choose 2) - (x choose 2) is equal to x. That's why we just add c to variable "res" (as you referred to that line), which indeed computes (c choose 2) incrementally. 

Thanks,

**Comment by qubotong** [comment]
Hi Vahid,
Thank you for the clarification. I was confused by the equation shown in this [slide](https://www.slideshare.net/SeyedVahidSaneiMehri/butterfly-counting-in-bipartite-networks-100424465/19?src=clipshare). I mistook the C(c[x], 2) with \frac{c[x]}{2}. 

Best.
